# Generated by Django 6.0.7 on 2026-08-05 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEquipmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.TextField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('equipment_list_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_equipment_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('build_sheet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'build_sheets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('make', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('owned_by', models.TextField(blank=True, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('asset_category', models.TextField(blank=True, null=True)),
                ('equipment_id', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.TextField(blank=True, null=True)),
                ('equipment_notes', models.TextField(blank=True, null=True)),
                ('part_compatibility', models.TextField(blank=True, null=True)),
                ('tires', models.TextField(blank=True, null=True)),
                ('manuals', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('build_sheet', models.IntegerField(blank=True, null=True)),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('alt_asset_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_quantity', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.TextField(blank=True, choices=[('Receive From Supplier', 'Receive From Supplier'), ('Issue', 'Issue'), ('Return to Supplier', 'Return to Supplier'), ('Return', 'Return')], null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeAndCleaningSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('minimum_quantity', models.BigIntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('in_stock_location', models.TextField(blank=True, null=True)),
                ('office_supply_transactions', models.TextField(blank=True, null=True)),
                ('on_hand', models.BigIntegerField(blank=True, null=True)),
                ('supply_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'office_and_cleaning_supplies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeAndCleaningSuppliesHasSuppliersGridView',
            fields=[
                ('pk', models.CompositePrimaryKey('office_and_cleaning_supplies_id', 'suppliers_grid_view_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'office_and_cleaning_supplies_has_suppliers_grid_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeSupplyTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_name', models.TextField(blank=True, null=True)),
                ('transaction_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'office_supply_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('part_description', models.TextField(blank=True, null=True)),
                ('in_stock_location', models.TextField(blank=True, null=True)),
                ('on_hand', models.BigIntegerField(blank=True, null=True)),
                ('equipment_fitment', models.TextField(blank=True, null=True)),
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('needs_reorder', models.IntegerField(blank=True, null=True)),
                ('reorder_point', models.IntegerField(blank=True, null=True)),
                ('reorder_quantity', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('alternate_supplier', models.TextField(blank=True, null=True)),
                ('cost_notes', models.TextField(blank=True, null=True)),
                ('brand_model', models.TextField(blank=True, null=True)),
                ('part_name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartsDiagrams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('diagram_description', models.TextField(blank=True, null=True)),
                ('component_part_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parts_diagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartsHasEquipmentList',
            fields=[
                ('pk', models.CompositePrimaryKey('parts_part_id', 'equipment_list_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'parts_has_equipment_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartsSuppliers',
            fields=[
                ('pk', models.CompositePrimaryKey('part_id', 'supplier_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('supplier_part_code', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'parts_suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_description', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('invoice_number', models.DecimalField(blank=True, decimal_places=1, max_digits=22, null=True)),
                ('po_number', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.TextField(blank=True, null=True)),
                ('shipper_packing_slip_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_order_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepairHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_needed', models.DateField(blank=True, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('svc_description', models.TextField(blank=True, null=True)),
                ('reported_by', models.TextField(blank=True, null=True)),
                ('asset_id', models.TextField(blank=True, null=True)),
                ('work_order_number', models.TextField(blank=True, null=True)),
                ('completed_by', models.TextField(blank=True, null=True)),
                ('mechanic_notes', models.TextField(blank=True, null=True)),
                ('hours_to_complete', models.FloatField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repair_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.TextField(blank=True, null=True)),
                ('sage_transaction_type', models.TextField(blank=True, null=True)),
                ('sage_description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('general_ledger_number', models.TextField(blank=True, null=True)),
                ('supplier_information', models.TextField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sage_equipment', models.TextField(blank=True, null=True)),
                ('data_source', models.TextField(blank=True, null=True)),
                ('import_batch_id', models.TextField(blank=True, null=True)),
                ('import_key', models.TextField(blank=True, null=True)),
                ('part_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sage_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('supplier_specialty', models.TextField(blank=True, null=True)),
                ('supplier_location', models.TextField(blank=True, null=True)),
                ('supplier_experience_notes', models.TextField(blank=True, null=True)),
                ('purchasing_notes', models.TextField(blank=True, null=True)),
                ('supplier_type', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('account_website_login_notes', models.TextField(blank=True, null=True)),
                ('credit_notes', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('parts', models.TextField(blank=True, null=True)),
                ('vendor_rating', models.TextField(blank=True, null=True)),
                ('contact_notes', models.TextField(blank=True, null=True)),
                ('account_with_vendor', models.TextField(blank=True, null=True)),
                ('misc_notes', models.TextField(blank=True, null=True)),
                ('fax_number', models.TextField(blank=True, null=True)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('vendor_logs', models.TextField(blank=True, null=True)),
                ('parts_2', models.TextField(blank=True, null=True)),
                ('parts_3', models.TextField(blank=True, null=True)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('purchase_order_history', models.IntegerField(blank=True, null=True)),
                ('record_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuppliersLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.TextField(blank=True, null=True)),
                ('log_entry', models.TextField(blank=True, null=True)),
                ('log_type', models.TextField(blank=True, null=True)),
                ('user', models.TextField(blank=True, null=True)),
                ('supplier_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('auto_generated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.suppliers')),
            ],
            options={
                'db_table': 'purchase_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('part', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='inventory.parts')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_line',
            },
        ),
    ]
